### ISSUE TITLE
Find a more convenient way of aliasing the Firefox versions

### ISSUE THREAD

**Issue by lonnen** [boxen/puppet-firefox#11]
making a separate issue from comments on issue #10 

I haven't found any good solutions. 

Here's what I have left to look into:
- ~~Investigate downloading from mozilla/bouncer instead, which serves downloads from firefox.com, etc. Should be faster (served from cdn) and have the latest info. At a glance it looks like this still links to a specific version number, which is problematic.~~
- Factor branches into a YAML file or similar so that only that needs to be updated.
- Factor out the scraper we use on mozilla/socorro into it's own service that can be queried

**Comment by jacobbednarz** [comment]
This module has been deprecated in favour of the [inbuilt Homebrew/Caskroom support](https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17).
